trigger:
  - master

pool: "default"

variables:
  resourceGroupName: 'gaal'
  location: 'Canada Central'

stages:
- stage: ValidateTemplates
  displayName: Validate ARM Templates
  jobs:
  - job: ValidateARMTemplates
    displayName: Validate ARM Templates
    steps:
      - task: AzureResourceManagerTemplateDeployment@3
        displayName: Validate Storage Template
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: 'Abonnement_Al(43b74e9f-9d96-4aa0-859d-e36e8ba472b9)'
          subscriptionId: '43b74e9f-9d96-4aa0-859d-e36e8ba472b9'
          action: 'Create Or Update Resource Group'
          resourceGroupName: '$(resourceGroupName)'
          location: '$(location)'
          templateLocation: 'Linked artifact'
          csmFile: '$(Build.SourcesDirectory)/storage/azuredeploy.json'
          csmParametersFile: '$(Build.SourcesDirectory)/storage/azuredeploy.parameters.json'
          deploymentMode: 'Validation'

      - task: AzureResourceManagerTemplateDeployment@3
        displayName: Validate Function App Template
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: 'Abonnement_Al(43b74e9f-9d96-4aa0-859d-e36e8ba472b9)'
          subscriptionId: '43b74e9f-9d96-4aa0-859d-e36e8ba472b9'
          action: 'Create Or Update Resource Group'
          resourceGroupName: '$(resourceGroupName)'
          location: '$(location)'
          templateLocation: 'Linked artifact'
          csmFile: '$(Build.SourcesDirectory)/functionApp/azuredeploy.json'
          csmParametersFile: '$(Build.SourcesDirectory)/functionApp/azuredeploy.parameters.json'
          deploymentMode: 'Validation'

      - task: AzureResourceManagerTemplateDeployment@3
        displayName: Validate Service Bus Template
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: 'Abonnement_Al(43b74e9f-9d96-4aa0-859d-e36e8ba472b9)'
          subscriptionId: '43b74e9f-9d96-4aa0-859d-e36e8ba472b9'
          action: 'Create Or Update Resource Group'
          resourceGroupName: '$(resourceGroupName)'
          location: '$(location)'
          templateLocation: 'Linked artifact'
          csmFile: '$(Build.SourcesDirectory)/serviceBus/azuredeploy.json'
          csmParametersFile: '$(Build.SourcesDirectory)/serviceBus/azuredeploy.parameters.json'
          deploymentMode: 'Validation'

- stage: Build
  displayName: Build Stage
  dependsOn: ValidateTemplates
  jobs:
  - job: BuildBlobFunction
    displayName: Build Blob Function
    steps:
      # Tests for BlobFunction
      - task: DotNetCoreCLI@2
        displayName: Restore BlobFunction Project and Tests
        inputs:
          command: 'restore'
          projects: |
            $(Build.SourcesDirectory)/BlobFunction/*.csproj
            $(Build.SourcesDirectory)/BlobFunction.Tests/*.csproj

      - task: DotNetCoreCLI@2
        displayName: Run BlobFunction Tests
        inputs:
          command: 'test'
          projects: '$(Build.SourcesDirectory)/BlobFunction.Tests/*.csproj'
          arguments: '--configuration Release'

      # Build and publ